// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDpUq4G2gUdqlfayVwtSBDTO57HMmHAY',
    appId: '1:961518837039:web:03da4abbe7d07f12c315da',
    messagingSenderId: '961518837039',
    projectId: 'sentinel-a5191',
    authDomain: 'sentinel-a5191.firebaseapp.com',
    databaseURL: 'https://sentinel-a5191-default-rtdb.firebaseio.com',
    storageBucket: 'sentinel-a5191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUX7-lALkIRAnYXckII1K-lsClkYG3f2U',
    appId: '1:961518837039:android:f7312c326cc6a85fc315da',
    messagingSenderId: '961518837039',
    projectId: 'sentinel-a5191',
    databaseURL: 'https://sentinel-a5191-default-rtdb.firebaseio.com',
    storageBucket: 'sentinel-a5191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_5RvnUp5Xr_2xL0ACKKRExY3VMZFLCuQ',
    appId: '1:961518837039:ios:9bbabf266792c747c315da',
    messagingSenderId: '961518837039',
    projectId: 'sentinel-a5191',
    databaseURL: 'https://sentinel-a5191-default-rtdb.firebaseio.com',
    storageBucket: 'sentinel-a5191.firebasestorage.app',
    iosClientId: '961518837039-2dt4qsm24i84bour9srfqp98hhs0cmkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsentinel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXnjx_LxU3hZtQHAPzUCxTUZalTZTuDEY',
    appId: '1:617067569331:ios:6daa418ac354d4a810d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    storageBucket: 'track-9f980.appspot.com',
    androidClientId: '617067569331-6j5svo9cpb7o6lpdq3unocjvb97pcrpd.apps.googleusercontent.com',
    iosClientId: '617067569331-2aph255p4a5omtf4kpd4tkpq83ehsrp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsentinel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-X1Nc2rLdB5WALn7_4NFbRdCX6EvyxqE',
    appId: '1:617067569331:web:440e28ac71db2e6110d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    authDomain: 'track-9f980.firebaseapp.com',
    storageBucket: 'track-9f980.appspot.com',
  );
}