// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-X1Nc2rLdB5WALn7_4NFbRdCX6EvyxqE',
    appId: '1:617067569331:web:0622837c32d6005b10d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    authDomain: 'track-9f980.firebaseapp.com',
    storageBucket: 'track-9f980.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPZGBXhtLs3A03hONYhGwF9TmsxTQuoio',
    appId: '1:617067569331:android:9767af2c01729faf10d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    storageBucket: 'track-9f980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXnjx_LxU3hZtQHAPzUCxTUZalTZTuDEY',
    appId: '1:617067569331:ios:6daa418ac354d4a810d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    storageBucket: 'track-9f980.appspot.com',
    androidClientId: '617067569331-6j5svo9cpb7o6lpdq3unocjvb97pcrpd.apps.googleusercontent.com',
    iosClientId: '617067569331-2aph255p4a5omtf4kpd4tkpq83ehsrp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsentinel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXnjx_LxU3hZtQHAPzUCxTUZalTZTuDEY',
    appId: '1:617067569331:ios:6daa418ac354d4a810d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    storageBucket: 'track-9f980.appspot.com',
    androidClientId: '617067569331-6j5svo9cpb7o6lpdq3unocjvb97pcrpd.apps.googleusercontent.com',
    iosClientId: '617067569331-2aph255p4a5omtf4kpd4tkpq83ehsrp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsentinel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-X1Nc2rLdB5WALn7_4NFbRdCX6EvyxqE',
    appId: '1:617067569331:web:440e28ac71db2e6110d0c6',
    messagingSenderId: '617067569331',
    projectId: 'track-9f980',
    authDomain: 'track-9f980.firebaseapp.com',
    storageBucket: 'track-9f980.appspot.com',
  );
}
